create database users;

create table USER(
    ID VARCHAR(32) PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    SURNAME VARCHAR(20) NOT NULL,
    AGE INTEGER NOT NULL,
    NICK VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(128)  NOT NULL,
    CREATION_TIME TIMESTAMP
);